dataset: HEAD_LARGE
data_root: data/FetalHeadLarge
splits_csv: splits/head_large_splits.csv
task: classification_regression
image_size: 224
patch_size: 16
model:
  d_model: 512
  ssm_depth: 4
  vit_depth: 6
  heads: 8
  mlp_ratio: 4
  use_fusion_gate: true
loss:
  use_uncertainty_weighting: true
  entropy_lambda: 0.001
  use_shape_consistency: false
optimizer:
  name: adam
  lr: 1.0e-4
  weight_decay: 0.0
train:
  epochs: 100
  batch_size: 16
  num_workers: 8
  aug: strong
eval:
  calibrate_temperature: true
seed: 42
save_dir: runs/head_large
classes: 5
